{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: primary
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.mysql.auth.existingSecret }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
