# MySQL Dockerfile
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root \
    MYSQL_DATABASE=appdb \
    MYSQL_USER=testuser \
    MYSQL_PASSWORD=testpassword

# Expose MySQL port
EXPOSE 3306
